from ctypes import *
import platform
import warnings

# Type definitions for callback usage
Callback = CFUNCTYPE(None, c_void_p)
CallbackDeviceList = CFUNCTYPE(None, c_void_p, c_uint32, c_uint32)


class Library:
    """This class implements an interface to the TiePie device library.

    Information on the specific functions can be found in the
    `library's api documentation <http://api.tiepie.com/libtiepie/>`_

    Attributes:
        libtiepie: :py:class:`ctypes.CDLL` instance of libtiepie.dll resp. libtiepie.so
    """

    def __init__(self):
        if platform.system() == 'Linux':
            library_name = 'libtiepie.so.0'
        elif platform.system() == 'Windows':
            from ctypes.wintypes import HANDLE, HWND, LPARAM, WPARAM
            library_name = 'libtiepie.dll'
        else:
            raise Exception('Can\'t determine library name, unknown platform.system(): ' + platform.system())

        self.libtiepie = CDLL(library_name)

        # define result and argument types
        self.libtiepie.LibInit.restype = None
        self.libtiepie.LibInit.argtypes = []
        self.libtiepie.LibInit.errcheck = self.check_status
        self.libtiepie.LibIsInitialized.restype = c_uint8
        self.libtiepie.LibIsInitialized.argtypes = []
        self.libtiepie.LibIsInitialized.errcheck = self.check_status
        self.libtiepie.LibExit.restype = None
        self.libtiepie.LibExit.argtypes = []
        self.libtiepie.LibExit.errcheck = self.check_status
        self.libtiepie.LibGetVersion.restype = c_uint64
        self.libtiepie.LibGetVersion.argtypes = []
        self.libtiepie.LibGetVersion.errcheck = self.check_status
        self.libtiepie.LibGetVersionExtra.restype = c_char_p
        self.libtiepie.LibGetVersionExtra.argtypes = []
        self.libtiepie.LibGetVersionExtra.errcheck = self.check_status
        self.libtiepie.LibGetConfig.restype = c_uint32
        self.libtiepie.LibGetConfig.argtypes = [c_void_p, c_uint32]
        self.libtiepie.LibGetConfig.errcheck = self.check_status
        self.libtiepie.LibGetLastStatus.restype = c_int32
        self.libtiepie.LibGetLastStatus.argtypes = []
        # no error check function for LibGetLastStatus to avoid infinite recursion
        self.libtiepie.LibGetLastStatusStr.restype = c_char_p
        self.libtiepie.LibGetLastStatusStr.argtypes = []
        # no error check function for LibGetLastStatusStr to avoid infinite recursion
        self.libtiepie.LstUpdate.restype = None
        self.libtiepie.LstUpdate.argtypes = []
        self.libtiepie.LstUpdate.errcheck = self.check_status
        self.libtiepie.LstGetCount.restype = c_uint32
        self.libtiepie.LstGetCount.argtypes = []
        self.libtiepie.LstGetCount.errcheck = self.check_status
        self.libtiepie.LstOpenDevice.restype = c_uint32
        self.libtiepie.LstOpenDevice.argtypes = [c_uint32, c_uint32, c_uint32]
        self.libtiepie.LstOpenDevice.errcheck = self.check_status
        self.libtiepie.LstOpenOscilloscope.restype = c_uint32
        self.libtiepie.LstOpenOscilloscope.argtypes = [c_uint32, c_uint32]
        self.libtiepie.LstOpenOscilloscope.errcheck = self.check_status
        self.libtiepie.LstOpenGenerator.restype = c_uint32
        self.libtiepie.LstOpenGenerator.argtypes = [c_uint32, c_uint32]
        self.libtiepie.LstOpenGenerator.errcheck = self.check_status
        self.libtiepie.LstOpenI2CHost.restype = c_uint32
        self.libtiepie.LstOpenI2CHost.argtypes = [c_uint32, c_uint32]
        self.libtiepie.LstOpenI2CHost.errcheck = self.check_status
        self.libtiepie.LstCreateCombinedDevice.restype = c_uint32
        self.libtiepie.LstCreateCombinedDevice.argtypes = [c_void_p, c_uint32]
        self.libtiepie.LstCreateCombinedDevice.errcheck = self.check_status
        self.libtiepie.LstCreateAndOpenCombinedDevice.restype = c_uint32
        self.libtiepie.LstCreateAndOpenCombinedDevice.argtypes = [c_void_p, c_uint32]
        self.libtiepie.LstCreateAndOpenCombinedDevice.errcheck = self.check_status
        self.libtiepie.LstRemoveDevice.restype = None
        self.libtiepie.LstRemoveDevice.argtypes = [c_uint32]
        self.libtiepie.LstRemoveDevice.errcheck = self.check_status
        self.libtiepie.LstDevCanOpen.restype = c_uint8
        self.libtiepie.LstDevCanOpen.argtypes = [c_uint32, c_uint32, c_uint32]
        self.libtiepie.LstDevCanOpen.errcheck = self.check_status
        self.libtiepie.LstDevGetProductId.restype = c_uint32
        self.libtiepie.LstDevGetProductId.argtypes = [c_uint32, c_uint32]
        self.libtiepie.LstDevGetProductId.errcheck = self.check_status
        self.libtiepie.LstDevGetVendorId.restype = c_uint32
        self.libtiepie.LstDevGetVendorId.argtypes = [c_uint32, c_uint32]
        self.libtiepie.LstDevGetVendorId.errcheck = self.check_status
        self.libtiepie.LstDevGetName.restype = c_uint32
        self.libtiepie.LstDevGetName.argtypes = [c_uint32, c_uint32, c_char_p, c_uint32]
        self.libtiepie.LstDevGetName.errcheck = self.check_status
        self.libtiepie.LstDevGetNameShort.restype = c_uint32
        self.libtiepie.LstDevGetNameShort.argtypes = [c_uint32, c_uint32, c_char_p, c_uint32]
        self.libtiepie.LstDevGetNameShort.errcheck = self.check_status
        self.libtiepie.LstDevGetNameShortest.restype = c_uint32
        self.libtiepie.LstDevGetNameShortest.argtypes = [c_uint32, c_uint32, c_char_p, c_uint32]
        self.libtiepie.LstDevGetNameShortest.errcheck = self.check_status
        self.libtiepie.LstDevGetDriverVersion.restype = c_uint64
        self.libtiepie.LstDevGetDriverVersion.argtypes = [c_uint32, c_uint32]
        self.libtiepie.LstDevGetDriverVersion.errcheck = self.check_status
        self.libtiepie.LstDevGetRecommendedDriverVersion.restype = c_uint64
        self.libtiepie.LstDevGetRecommendedDriverVersion.argtypes = [c_uint32, c_uint32]
        self.libtiepie.LstDevGetRecommendedDriverVersion.errcheck = self.check_status
        self.libtiepie.LstDevGetFirmwareVersion.restype = c_uint64
        self.libtiepie.LstDevGetFirmwareVersion.argtypes = [c_uint32, c_uint32]
        self.libtiepie.LstDevGetFirmwareVersion.errcheck = self.check_status
        self.libtiepie.LstDevGetRecommendedFirmwareVersion.restype = c_uint64
        self.libtiepie.LstDevGetRecommendedFirmwareVersion.argtypes = [c_uint32, c_uint32]
        self.libtiepie.LstDevGetRecommendedFirmwareVersion.errcheck = self.check_status
        self.libtiepie.LstDevGetCalibrationDate.restype = c_uint32
        self.libtiepie.LstDevGetCalibrationDate.argtypes = [c_uint32, c_uint32]
        self.libtiepie.LstDevGetCalibrationDate.errcheck = self.check_status
        self.libtiepie.LstDevGetSerialNumber.restype = c_uint32
        self.libtiepie.LstDevGetSerialNumber.argtypes = [c_uint32, c_uint32]
        self.libtiepie.LstDevGetSerialNumber.errcheck = self.check_status
        self.libtiepie.LstDevGetTypes.restype = c_uint32
        self.libtiepie.LstDevGetTypes.argtypes = [c_uint32, c_uint32]
        self.libtiepie.LstDevGetTypes.errcheck = self.check_status
        self.libtiepie.LstDevGetContainedSerialNumbers.restype = c_uint32
        self.libtiepie.LstDevGetContainedSerialNumbers.argtypes = [c_uint32, c_uint32, c_void_p, c_uint32]
        self.libtiepie.LstDevGetContainedSerialNumbers.errcheck = self.check_status
        self.libtiepie.LstCbDevGetProductId.restype = c_uint32
        self.libtiepie.LstCbDevGetProductId.argtypes = [c_uint32, c_uint32, c_uint32]
        self.libtiepie.LstCbDevGetProductId.errcheck = self.check_status
        self.libtiepie.LstCbDevGetVendorId.restype = c_uint32
        self.libtiepie.LstCbDevGetVendorId.argtypes = [c_uint32, c_uint32, c_uint32]
        self.libtiepie.LstCbDevGetVendorId.errcheck = self.check_status
        self.libtiepie.LstCbDevGetName.restype = c_uint32
        self.libtiepie.LstCbDevGetName.argtypes = [c_uint32, c_uint32, c_uint32, c_char_p, c_uint32]
        self.libtiepie.LstCbDevGetName.errcheck = self.check_status
        self.libtiepie.LstCbDevGetNameShort.restype = c_uint32
        self.libtiepie.LstCbDevGetNameShort.argtypes = [c_uint32, c_uint32, c_uint32, c_char_p, c_uint32]
        self.libtiepie.LstCbDevGetNameShort.errcheck = self.check_status
        self.libtiepie.LstCbDevGetNameShortest.restype = c_uint32
        self.libtiepie.LstCbDevGetNameShortest.argtypes = [c_uint32, c_uint32, c_uint32, c_char_p, c_uint32]
        self.libtiepie.LstCbDevGetNameShortest.errcheck = self.check_status
        self.libtiepie.LstCbDevGetDriverVersion.restype = c_uint64
        self.libtiepie.LstCbDevGetDriverVersion.argtypes = [c_uint32, c_uint32, c_uint32]
        self.libtiepie.LstCbDevGetDriverVersion.errcheck = self.check_status
        self.libtiepie.LstCbDevGetFirmwareVersion.restype = c_uint64
        self.libtiepie.LstCbDevGetFirmwareVersion.argtypes = [c_uint32, c_uint32, c_uint32]
        self.libtiepie.LstCbDevGetFirmwareVersion.errcheck = self.check_status
        self.libtiepie.LstCbDevGetCalibrationDate.restype = c_uint32
        self.libtiepie.LstCbDevGetCalibrationDate.argtypes = [c_uint32, c_uint32, c_uint32]
        self.libtiepie.LstCbDevGetCalibrationDate.errcheck = self.check_status
        self.libtiepie.LstCbScpGetChannelCount.restype = c_uint16
        self.libtiepie.LstCbScpGetChannelCount.argtypes = [c_uint32, c_uint32, c_uint32]
        self.libtiepie.LstCbScpGetChannelCount.errcheck = self.check_status
        self.libtiepie.LstSetCallbackDeviceAdded.restype = None
        self.libtiepie.LstSetCallbackDeviceAdded.argtypes = [CallbackDeviceList, c_void_p]
        self.libtiepie.LstSetCallbackDeviceAdded.errcheck = self.check_status
        self.libtiepie.LstSetCallbackDeviceRemoved.restype = None
        self.libtiepie.LstSetCallbackDeviceRemoved.argtypes = [CallbackDeviceList, c_void_p]
        self.libtiepie.LstSetCallbackDeviceRemoved.errcheck = self.check_status
        if platform.system() == 'Linux':
            self.libtiepie.LstSetEventDeviceAdded.restype = None
            self.libtiepie.LstSetEventDeviceAdded.argtypes = [c_int]
            self.libtiepie.LstSetEventDeviceAdded.errcheck = self.check_status
            self.libtiepie.LstSetEventDeviceRemoved.restype = None
            self.libtiepie.LstSetEventDeviceRemoved.argtypes = [c_int]
            self.libtiepie.LstSetEventDeviceRemoved.errcheck = self.check_status
        if platform.system() == 'Windows':
            self.libtiepie.LstSetEventDeviceAdded.restype = None
            self.libtiepie.LstSetEventDeviceAdded.argtypes = [HANDLE]
            self.libtiepie.LstSetEventDeviceAdded.errcheck = self.check_status
            self.libtiepie.LstSetEventDeviceRemoved.restype = None
            self.libtiepie.LstSetEventDeviceRemoved.argtypes = [HANDLE]
            self.libtiepie.LstSetEventDeviceRemoved.errcheck = self.check_status
            self.libtiepie.LstSetMessageDeviceAdded.restype = None
            self.libtiepie.LstSetMessageDeviceAdded.argtypes = [HWND]
            self.libtiepie.LstSetMessageDeviceAdded.errcheck = self.check_status
            self.libtiepie.LstSetMessageDeviceRemoved.restype = None
            self.libtiepie.LstSetMessageDeviceRemoved.argtypes = [HWND]
            self.libtiepie.LstSetMessageDeviceRemoved.errcheck = self.check_status
        self.libtiepie.DevClose.restype = None
        self.libtiepie.DevClose.argtypes = [c_uint32]
        self.libtiepie.DevClose.errcheck = self.check_status
        self.libtiepie.DevIsRemoved.restype = c_uint8
        self.libtiepie.DevIsRemoved.argtypes = [c_uint32]
        self.libtiepie.DevIsRemoved.errcheck = self.check_status
        self.libtiepie.DevGetDriverVersion.restype = c_uint64
        self.libtiepie.DevGetDriverVersion.argtypes = [c_uint32]
        self.libtiepie.DevGetDriverVersion.errcheck = self.check_status
        self.libtiepie.DevGetFirmwareVersion.restype = c_uint64
        self.libtiepie.DevGetFirmwareVersion.argtypes = [c_uint32]
        self.libtiepie.DevGetFirmwareVersion.errcheck = self.check_status
        self.libtiepie.DevGetCalibrationDate.restype = c_uint32
        self.libtiepie.DevGetCalibrationDate.argtypes = [c_uint32]
        self.libtiepie.DevGetCalibrationDate.errcheck = self.check_status
        self.libtiepie.DevGetSerialNumber.restype = c_uint32
        self.libtiepie.DevGetSerialNumber.argtypes = [c_uint32]
        self.libtiepie.DevGetSerialNumber.errcheck = self.check_status
        self.libtiepie.DevGetProductId.restype = c_uint32
        self.libtiepie.DevGetProductId.argtypes = [c_uint32]
        self.libtiepie.DevGetProductId.errcheck = self.check_status
        self.libtiepie.DevGetVendorId.restype = c_uint32
        self.libtiepie.DevGetVendorId.argtypes = [c_uint32]
        self.libtiepie.DevGetVendorId.errcheck = self.check_status
        self.libtiepie.DevGetType.restype = c_uint32
        self.libtiepie.DevGetType.argtypes = [c_uint32]
        self.libtiepie.DevGetType.errcheck = self.check_status
        self.libtiepie.DevGetName.restype = c_uint32
        self.libtiepie.DevGetName.argtypes = [c_uint32, c_char_p, c_uint32]
        self.libtiepie.DevGetName.errcheck = self.check_status
        self.libtiepie.DevGetNameShort.restype = c_uint32
        self.libtiepie.DevGetNameShort.argtypes = [c_uint32, c_char_p, c_uint32]
        self.libtiepie.DevGetNameShort.errcheck = self.check_status
        self.libtiepie.DevGetNameShortest.restype = c_uint32
        self.libtiepie.DevGetNameShortest.argtypes = [c_uint32, c_char_p, c_uint32]
        self.libtiepie.DevGetNameShortest.errcheck = self.check_status
        self.libtiepie.DevSetCallbackRemoved.restype = None
        self.libtiepie.DevSetCallbackRemoved.argtypes = [c_uint32, Callback, c_void_p]
        self.libtiepie.DevSetCallbackRemoved.errcheck = self.check_status
        if platform.system() == 'Linux':
            self.libtiepie.DevSetEventRemoved.restype = None
            self.libtiepie.DevSetEventRemoved.argtypes = [c_uint32, c_int]
            self.libtiepie.DevSetEventRemoved.errcheck = self.check_status
        if platform.system() == 'Windows':
            self.libtiepie.DevSetEventRemoved.restype = None
            self.libtiepie.DevSetEventRemoved.argtypes = [c_uint32, HANDLE]
            self.libtiepie.DevSetEventRemoved.errcheck = self.check_status
            self.libtiepie.DevSetMessageRemoved.restype = None
            self.libtiepie.DevSetMessageRemoved.argtypes = [c_uint32, HWND, WPARAM, LPARAM]
            self.libtiepie.DevSetMessageRemoved.errcheck = self.check_status
        self.libtiepie.DevTrGetInputCount.restype = c_uint16
        self.libtiepie.DevTrGetInputCount.argtypes = [c_uint32]
        self.libtiepie.DevTrGetInputCount.errcheck = self.check_status
        self.libtiepie.DevTrGetInputIndexById.restype = c_uint16
        self.libtiepie.DevTrGetInputIndexById.argtypes = [c_uint32, c_uint32]
        self.libtiepie.DevTrGetInputIndexById.errcheck = self.check_status
        self.libtiepie.ScpTrInIsTriggered.restype = c_uint8
        self.libtiepie.ScpTrInIsTriggered.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpTrInIsTriggered.errcheck = self.check_status
        self.libtiepie.DevTrInGetEnabled.restype = c_uint8
        self.libtiepie.DevTrInGetEnabled.argtypes = [c_uint32, c_uint16]
        self.libtiepie.DevTrInGetEnabled.errcheck = self.check_status
        self.libtiepie.DevTrInSetEnabled.restype = c_uint8
        self.libtiepie.DevTrInSetEnabled.argtypes = [c_uint32, c_uint16, c_uint8]
        self.libtiepie.DevTrInSetEnabled.errcheck = self.check_status
        self.libtiepie.DevTrInGetKinds.restype = c_uint64
        self.libtiepie.DevTrInGetKinds.argtypes = [c_uint32, c_uint16]
        self.libtiepie.DevTrInGetKinds.errcheck = self.check_status
        self.libtiepie.ScpTrInGetKindsEx.restype = c_uint64
        self.libtiepie.ScpTrInGetKindsEx.argtypes = [c_uint32, c_uint16, c_uint32]
        self.libtiepie.ScpTrInGetKindsEx.errcheck = self.check_status
        self.libtiepie.DevTrInGetKind.restype = c_uint64
        self.libtiepie.DevTrInGetKind.argtypes = [c_uint32, c_uint16]
        self.libtiepie.DevTrInGetKind.errcheck = self.check_status
        self.libtiepie.DevTrInSetKind.restype = c_uint64
        self.libtiepie.DevTrInSetKind.argtypes = [c_uint32, c_uint16, c_uint64]
        self.libtiepie.DevTrInSetKind.errcheck = self.check_status
        self.libtiepie.DevTrInIsAvailable.restype = c_uint8
        self.libtiepie.DevTrInIsAvailable.argtypes = [c_uint32, c_uint16]
        self.libtiepie.DevTrInIsAvailable.errcheck = self.check_status
        self.libtiepie.ScpTrInIsAvailableEx.restype = c_uint8
        self.libtiepie.ScpTrInIsAvailableEx.argtypes = [c_uint32, c_uint16, c_uint32]
        self.libtiepie.ScpTrInIsAvailableEx.errcheck = self.check_status
        self.libtiepie.DevTrInGetId.restype = c_uint32
        self.libtiepie.DevTrInGetId.argtypes = [c_uint32, c_uint16]
        self.libtiepie.DevTrInGetId.errcheck = self.check_status
        self.libtiepie.DevTrInGetName.restype = c_uint32
        self.libtiepie.DevTrInGetName.argtypes = [c_uint32, c_uint16, c_char_p, c_uint32]
        self.libtiepie.DevTrInGetName.errcheck = self.check_status
        self.libtiepie.DevTrGetOutputCount.restype = c_uint16
        self.libtiepie.DevTrGetOutputCount.argtypes = [c_uint32]
        self.libtiepie.DevTrGetOutputCount.errcheck = self.check_status
        self.libtiepie.DevTrGetOutputIndexById.restype = c_uint16
        self.libtiepie.DevTrGetOutputIndexById.argtypes = [c_uint32, c_uint32]
        self.libtiepie.DevTrGetOutputIndexById.errcheck = self.check_status
        self.libtiepie.DevTrOutGetEnabled.restype = c_uint8
        self.libtiepie.DevTrOutGetEnabled.argtypes = [c_uint32, c_uint16]
        self.libtiepie.DevTrOutGetEnabled.errcheck = self.check_status
        self.libtiepie.DevTrOutSetEnabled.restype = c_uint8
        self.libtiepie.DevTrOutSetEnabled.argtypes = [c_uint32, c_uint16, c_uint8]
        self.libtiepie.DevTrOutSetEnabled.errcheck = self.check_status
        self.libtiepie.DevTrOutGetEvents.restype = c_uint64
        self.libtiepie.DevTrOutGetEvents.argtypes = [c_uint32, c_uint16]
        self.libtiepie.DevTrOutGetEvents.errcheck = self.check_status
        self.libtiepie.DevTrOutGetEvent.restype = c_uint64
        self.libtiepie.DevTrOutGetEvent.argtypes = [c_uint32, c_uint16]
        self.libtiepie.DevTrOutGetEvent.errcheck = self.check_status
        self.libtiepie.DevTrOutSetEvent.restype = c_uint64
        self.libtiepie.DevTrOutSetEvent.argtypes = [c_uint32, c_uint16, c_uint64]
        self.libtiepie.DevTrOutSetEvent.errcheck = self.check_status
        self.libtiepie.DevTrOutGetId.restype = c_uint32
        self.libtiepie.DevTrOutGetId.argtypes = [c_uint32, c_uint16]
        self.libtiepie.DevTrOutGetId.errcheck = self.check_status
        self.libtiepie.DevTrOutGetName.restype = c_uint32
        self.libtiepie.DevTrOutGetName.argtypes = [c_uint32, c_uint16, c_char_p, c_uint32]
        self.libtiepie.DevTrOutGetName.errcheck = self.check_status
        self.libtiepie.ScpGetChannelCount.restype = c_uint16
        self.libtiepie.ScpGetChannelCount.argtypes = [c_uint32]
        self.libtiepie.ScpGetChannelCount.errcheck = self.check_status
        self.libtiepie.ScpChIsAvailable.restype = c_uint8
        self.libtiepie.ScpChIsAvailable.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChIsAvailable.errcheck = self.check_status
        self.libtiepie.ScpChIsAvailableEx.restype = c_uint8
        self.libtiepie.ScpChIsAvailableEx.argtypes = [c_uint32, c_uint16, c_uint32, c_double, c_uint8, c_void_p,
                                                      c_uint16]
        self.libtiepie.ScpChIsAvailableEx.errcheck = self.check_status
        self.libtiepie.ScpChGetConnectorType.restype = c_uint32
        self.libtiepie.ScpChGetConnectorType.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChGetConnectorType.errcheck = self.check_status
        self.libtiepie.ScpChIsDifferential.restype = c_uint8
        self.libtiepie.ScpChIsDifferential.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChIsDifferential.errcheck = self.check_status
        self.libtiepie.ScpChGetImpedance.restype = c_double
        self.libtiepie.ScpChGetImpedance.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChGetImpedance.errcheck = self.check_status
        self.libtiepie.ScpChGetCouplings.restype = c_uint64
        self.libtiepie.ScpChGetCouplings.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChGetCouplings.errcheck = self.check_status
        self.libtiepie.ScpChGetCoupling.restype = c_uint64
        self.libtiepie.ScpChGetCoupling.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChGetCoupling.errcheck = self.check_status
        self.libtiepie.ScpChSetCoupling.restype = c_uint64
        self.libtiepie.ScpChSetCoupling.argtypes = [c_uint32, c_uint16, c_uint64]
        self.libtiepie.ScpChSetCoupling.errcheck = self.check_status
        self.libtiepie.ScpChGetEnabled.restype = c_uint8
        self.libtiepie.ScpChGetEnabled.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChGetEnabled.errcheck = self.check_status
        self.libtiepie.ScpChSetEnabled.restype = c_uint8
        self.libtiepie.ScpChSetEnabled.argtypes = [c_uint32, c_uint16, c_uint8]
        self.libtiepie.ScpChSetEnabled.errcheck = self.check_status
        self.libtiepie.ScpChGetProbeGain.restype = c_double
        self.libtiepie.ScpChGetProbeGain.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChGetProbeGain.errcheck = self.check_status
        self.libtiepie.ScpChSetProbeGain.restype = c_double
        self.libtiepie.ScpChSetProbeGain.argtypes = [c_uint32, c_uint16, c_double]
        self.libtiepie.ScpChSetProbeGain.errcheck = self.check_status
        self.libtiepie.ScpChGetProbeOffset.restype = c_double
        self.libtiepie.ScpChGetProbeOffset.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChGetProbeOffset.errcheck = self.check_status
        self.libtiepie.ScpChSetProbeOffset.restype = c_double
        self.libtiepie.ScpChSetProbeOffset.argtypes = [c_uint32, c_uint16, c_double]
        self.libtiepie.ScpChSetProbeOffset.errcheck = self.check_status
        self.libtiepie.ScpChGetAutoRanging.restype = c_uint8
        self.libtiepie.ScpChGetAutoRanging.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChGetAutoRanging.errcheck = self.check_status
        self.libtiepie.ScpChSetAutoRanging.restype = c_uint8
        self.libtiepie.ScpChSetAutoRanging.argtypes = [c_uint32, c_uint16, c_uint8]
        self.libtiepie.ScpChSetAutoRanging.errcheck = self.check_status
        self.libtiepie.ScpChGetRanges.restype = c_uint32
        self.libtiepie.ScpChGetRanges.argtypes = [c_uint32, c_uint16, c_void_p, c_uint32]
        self.libtiepie.ScpChGetRanges.errcheck = self.check_status
        self.libtiepie.ScpChGetRangesEx.restype = c_uint32
        self.libtiepie.ScpChGetRangesEx.argtypes = [c_uint32, c_uint16, c_uint64, c_void_p, c_uint32]
        self.libtiepie.ScpChGetRangesEx.errcheck = self.check_status
        self.libtiepie.ScpChGetRange.restype = c_double
        self.libtiepie.ScpChGetRange.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChGetRange.errcheck = self.check_status
        self.libtiepie.ScpChSetRange.restype = c_double
        self.libtiepie.ScpChSetRange.argtypes = [c_uint32, c_uint16, c_double]
        self.libtiepie.ScpChSetRange.errcheck = self.check_status
        self.libtiepie.ScpChHasTrigger.restype = c_uint8
        self.libtiepie.ScpChHasTrigger.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChHasTrigger.errcheck = self.check_status
        self.libtiepie.ScpChHasTriggerEx.restype = c_uint8
        self.libtiepie.ScpChHasTriggerEx.argtypes = [c_uint32, c_uint16, c_uint32]
        self.libtiepie.ScpChHasTriggerEx.errcheck = self.check_status
        self.libtiepie.ScpChTrIsAvailable.restype = c_uint8
        self.libtiepie.ScpChTrIsAvailable.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChTrIsAvailable.errcheck = self.check_status
        self.libtiepie.ScpChTrIsAvailableEx.restype = c_uint8
        self.libtiepie.ScpChTrIsAvailableEx.argtypes = [c_uint32, c_uint16, c_uint32, c_double, c_uint8, c_void_p,
                                                        c_void_p, c_uint16]
        self.libtiepie.ScpChTrIsAvailableEx.errcheck = self.check_status
        self.libtiepie.ScpChTrIsTriggered.restype = c_uint8
        self.libtiepie.ScpChTrIsTriggered.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChTrIsTriggered.errcheck = self.check_status
        self.libtiepie.ScpChTrGetEnabled.restype = c_uint8
        self.libtiepie.ScpChTrGetEnabled.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChTrGetEnabled.errcheck = self.check_status
        self.libtiepie.ScpChTrSetEnabled.restype = c_uint8
        self.libtiepie.ScpChTrSetEnabled.argtypes = [c_uint32, c_uint16, c_uint8]
        self.libtiepie.ScpChTrSetEnabled.errcheck = self.check_status
        self.libtiepie.ScpChTrGetKinds.restype = c_uint64
        self.libtiepie.ScpChTrGetKinds.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChTrGetKinds.errcheck = self.check_status
        self.libtiepie.ScpChTrGetKindsEx.restype = c_uint64
        self.libtiepie.ScpChTrGetKindsEx.argtypes = [c_uint32, c_uint16, c_uint32]
        self.libtiepie.ScpChTrGetKindsEx.errcheck = self.check_status
        self.libtiepie.ScpChTrGetKind.restype = c_uint64
        self.libtiepie.ScpChTrGetKind.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChTrGetKind.errcheck = self.check_status
        self.libtiepie.ScpChTrSetKind.restype = c_uint64
        self.libtiepie.ScpChTrSetKind.argtypes = [c_uint32, c_uint16, c_uint64]
        self.libtiepie.ScpChTrSetKind.errcheck = self.check_status
        self.libtiepie.ScpChTrGetLevelCount.restype = c_uint32
        self.libtiepie.ScpChTrGetLevelCount.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChTrGetLevelCount.errcheck = self.check_status
        self.libtiepie.ScpChTrGetLevel.restype = c_double
        self.libtiepie.ScpChTrGetLevel.argtypes = [c_uint32, c_uint16, c_uint32]
        self.libtiepie.ScpChTrGetLevel.errcheck = self.check_status
        self.libtiepie.ScpChTrSetLevel.restype = c_double
        self.libtiepie.ScpChTrSetLevel.argtypes = [c_uint32, c_uint16, c_uint32, c_double]
        self.libtiepie.ScpChTrSetLevel.errcheck = self.check_status
        self.libtiepie.ScpChTrGetHysteresisCount.restype = c_uint32
        self.libtiepie.ScpChTrGetHysteresisCount.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChTrGetHysteresisCount.errcheck = self.check_status
        self.libtiepie.ScpChTrGetHysteresis.restype = c_double
        self.libtiepie.ScpChTrGetHysteresis.argtypes = [c_uint32, c_uint16, c_uint32]
        self.libtiepie.ScpChTrGetHysteresis.errcheck = self.check_status
        self.libtiepie.ScpChTrSetHysteresis.restype = c_double
        self.libtiepie.ScpChTrSetHysteresis.argtypes = [c_uint32, c_uint16, c_uint32, c_double]
        self.libtiepie.ScpChTrSetHysteresis.errcheck = self.check_status
        self.libtiepie.ScpChTrGetConditions.restype = c_uint32
        self.libtiepie.ScpChTrGetConditions.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChTrGetConditions.errcheck = self.check_status
        self.libtiepie.ScpChTrGetConditionsEx.restype = c_uint32
        self.libtiepie.ScpChTrGetConditionsEx.argtypes = [c_uint32, c_uint16, c_uint32, c_uint64]
        self.libtiepie.ScpChTrGetConditionsEx.errcheck = self.check_status
        self.libtiepie.ScpChTrGetCondition.restype = c_uint32
        self.libtiepie.ScpChTrGetCondition.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChTrGetCondition.errcheck = self.check_status
        self.libtiepie.ScpChTrSetCondition.restype = c_uint32
        self.libtiepie.ScpChTrSetCondition.argtypes = [c_uint32, c_uint16, c_uint32]
        self.libtiepie.ScpChTrSetCondition.errcheck = self.check_status
        self.libtiepie.ScpChTrGetTimeCount.restype = c_uint32
        self.libtiepie.ScpChTrGetTimeCount.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChTrGetTimeCount.errcheck = self.check_status
        self.libtiepie.ScpChTrGetTime.restype = c_double
        self.libtiepie.ScpChTrGetTime.argtypes = [c_uint32, c_uint16, c_uint32]
        self.libtiepie.ScpChTrGetTime.errcheck = self.check_status
        self.libtiepie.ScpChTrSetTime.restype = c_double
        self.libtiepie.ScpChTrSetTime.argtypes = [c_uint32, c_uint16, c_uint32, c_double]
        self.libtiepie.ScpChTrSetTime.errcheck = self.check_status
        self.libtiepie.ScpChTrVerifyTime.restype = c_double
        self.libtiepie.ScpChTrVerifyTime.argtypes = [c_uint32, c_uint16, c_uint32, c_double]
        self.libtiepie.ScpChTrVerifyTime.errcheck = self.check_status
        self.libtiepie.ScpChTrVerifyTimeEx2.restype = c_double
        self.libtiepie.ScpChTrVerifyTimeEx2.argtypes = [c_uint32, c_uint16, c_uint32, c_double, c_uint32, c_double,
                                                        c_uint64, c_uint32]
        self.libtiepie.ScpChTrVerifyTimeEx2.errcheck = self.check_status
        self.libtiepie.ScpGetData.restype = c_uint64
        self.libtiepie.ScpGetData.argtypes = [c_uint32, c_void_p, c_uint16, c_uint64, c_uint64]
        self.libtiepie.ScpGetData.errcheck = self.check_status
        self.libtiepie.ScpGetData1Ch.restype = c_uint64
        self.libtiepie.ScpGetData1Ch.argtypes = [c_uint32, c_void_p, c_uint64, c_uint64]
        self.libtiepie.ScpGetData1Ch.errcheck = self.check_status
        self.libtiepie.ScpGetData2Ch.restype = c_uint64
        self.libtiepie.ScpGetData2Ch.argtypes = [c_uint32, c_void_p, c_void_p, c_uint64, c_uint64]
        self.libtiepie.ScpGetData2Ch.errcheck = self.check_status
        self.libtiepie.ScpGetData3Ch.restype = c_uint64
        self.libtiepie.ScpGetData3Ch.argtypes = [c_uint32, c_void_p, c_void_p, c_void_p, c_uint64, c_uint64]
        self.libtiepie.ScpGetData3Ch.errcheck = self.check_status
        self.libtiepie.ScpGetData4Ch.restype = c_uint64
        self.libtiepie.ScpGetData4Ch.argtypes = [c_uint32, c_void_p, c_void_p, c_void_p, c_void_p, c_uint64, c_uint64]
        self.libtiepie.ScpGetData4Ch.errcheck = self.check_status
        self.libtiepie.ScpGetValidPreSampleCount.restype = c_uint64
        self.libtiepie.ScpGetValidPreSampleCount.argtypes = [c_uint32]
        self.libtiepie.ScpGetValidPreSampleCount.errcheck = self.check_status
        self.libtiepie.ScpChGetDataValueRange.restype = None
        self.libtiepie.ScpChGetDataValueRange.argtypes = [c_uint32, c_uint16, c_void_p, c_void_p]
        self.libtiepie.ScpChGetDataValueRange.errcheck = self.check_status
        self.libtiepie.ScpChGetDataValueMin.restype = c_double
        self.libtiepie.ScpChGetDataValueMin.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChGetDataValueMin.errcheck = self.check_status
        self.libtiepie.ScpChGetDataValueMax.restype = c_double
        self.libtiepie.ScpChGetDataValueMax.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChGetDataValueMax.errcheck = self.check_status
        self.libtiepie.ScpGetDataRaw.restype = c_uint64
        self.libtiepie.ScpGetDataRaw.argtypes = [c_uint32, c_void_p, c_uint16, c_uint64, c_uint64]
        self.libtiepie.ScpGetDataRaw.errcheck = self.check_status
        self.libtiepie.ScpGetDataRaw1Ch.restype = c_uint64
        self.libtiepie.ScpGetDataRaw1Ch.argtypes = [c_uint32, c_void_p, c_uint64, c_uint64]
        self.libtiepie.ScpGetDataRaw1Ch.errcheck = self.check_status
        self.libtiepie.ScpGetDataRaw2Ch.restype = c_uint64
        self.libtiepie.ScpGetDataRaw2Ch.argtypes = [c_uint32, c_void_p, c_void_p, c_uint64, c_uint64]
        self.libtiepie.ScpGetDataRaw2Ch.errcheck = self.check_status
        self.libtiepie.ScpGetDataRaw3Ch.restype = c_uint64
        self.libtiepie.ScpGetDataRaw3Ch.argtypes = [c_uint32, c_void_p, c_void_p, c_void_p, c_uint64, c_uint64]
        self.libtiepie.ScpGetDataRaw3Ch.errcheck = self.check_status
        self.libtiepie.ScpGetDataRaw4Ch.restype = c_uint64
        self.libtiepie.ScpGetDataRaw4Ch.argtypes = [c_uint32, c_void_p, c_void_p, c_void_p, c_void_p, c_uint64,
                                                    c_uint64]
        self.libtiepie.ScpGetDataRaw4Ch.errcheck = self.check_status
        self.libtiepie.ScpChGetDataRawType.restype = c_uint32
        self.libtiepie.ScpChGetDataRawType.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChGetDataRawType.errcheck = self.check_status
        self.libtiepie.ScpChGetDataRawValueRange.restype = None
        self.libtiepie.ScpChGetDataRawValueRange.argtypes = [c_uint32, c_uint16, c_void_p, c_void_p, c_void_p]
        self.libtiepie.ScpChGetDataRawValueRange.errcheck = self.check_status
        self.libtiepie.ScpChGetDataRawValueMin.restype = c_int64
        self.libtiepie.ScpChGetDataRawValueMin.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChGetDataRawValueMin.errcheck = self.check_status
        self.libtiepie.ScpChGetDataRawValueZero.restype = c_int64
        self.libtiepie.ScpChGetDataRawValueZero.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChGetDataRawValueZero.errcheck = self.check_status
        self.libtiepie.ScpChGetDataRawValueMax.restype = c_int64
        self.libtiepie.ScpChGetDataRawValueMax.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChGetDataRawValueMax.errcheck = self.check_status
        self.libtiepie.ScpChIsRangeMaxReachable.restype = c_uint8
        self.libtiepie.ScpChIsRangeMaxReachable.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChIsRangeMaxReachable.errcheck = self.check_status
        self.libtiepie.ScpSetCallbackDataReady.restype = None
        self.libtiepie.ScpSetCallbackDataReady.argtypes = [c_uint32, Callback, c_void_p]
        self.libtiepie.ScpSetCallbackDataReady.errcheck = self.check_status
        self.libtiepie.ScpSetCallbackDataOverflow.restype = None
        self.libtiepie.ScpSetCallbackDataOverflow.argtypes = [c_uint32, Callback, c_void_p]
        self.libtiepie.ScpSetCallbackDataOverflow.errcheck = self.check_status
        self.libtiepie.ScpSetCallbackConnectionTestCompleted.restype = None
        self.libtiepie.ScpSetCallbackConnectionTestCompleted.argtypes = [c_uint32, Callback, c_void_p]
        self.libtiepie.ScpSetCallbackConnectionTestCompleted.errcheck = self.check_status
        self.libtiepie.ScpSetCallbackTriggered.restype = None
        self.libtiepie.ScpSetCallbackTriggered.argtypes = [c_uint32, Callback, c_void_p]
        self.libtiepie.ScpSetCallbackTriggered.errcheck = self.check_status
        if platform.system() == 'Linux':
            self.libtiepie.ScpSetEventDataReady.restype = None
            self.libtiepie.ScpSetEventDataReady.argtypes = [c_uint32, c_int]
            self.libtiepie.ScpSetEventDataReady.errcheck = self.check_status
            self.libtiepie.ScpSetEventDataOverflow.restype = None
            self.libtiepie.ScpSetEventDataOverflow.argtypes = [c_uint32, c_int]
            self.libtiepie.ScpSetEventDataOverflow.errcheck = self.check_status
            self.libtiepie.ScpSetEventConnectionTestCompleted.restype = None
            self.libtiepie.ScpSetEventConnectionTestCompleted.argtypes = [c_uint32, c_int]
            self.libtiepie.ScpSetEventConnectionTestCompleted.errcheck = self.check_status
            self.libtiepie.ScpSetEventTriggered.restype = None
            self.libtiepie.ScpSetEventTriggered.argtypes = [c_uint32, c_int]
            self.libtiepie.ScpSetEventTriggered.errcheck = self.check_status
        if platform.system() == 'Windows':
            self.libtiepie.ScpSetEventDataReady.restype = None
            self.libtiepie.ScpSetEventDataReady.argtypes = [c_uint32, HANDLE]
            self.libtiepie.ScpSetEventDataReady.errcheck = self.check_status
            self.libtiepie.ScpSetEventDataOverflow.restype = None
            self.libtiepie.ScpSetEventDataOverflow.argtypes = [c_uint32, HANDLE]
            self.libtiepie.ScpSetEventDataOverflow.errcheck = self.check_status
            self.libtiepie.ScpSetEventConnectionTestCompleted.restype = None
            self.libtiepie.ScpSetEventConnectionTestCompleted.argtypes = [c_uint32, HANDLE]
            self.libtiepie.ScpSetEventConnectionTestCompleted.errcheck = self.check_status
            self.libtiepie.ScpSetEventTriggered.restype = None
            self.libtiepie.ScpSetEventTriggered.argtypes = [c_uint32, HANDLE]
            self.libtiepie.ScpSetEventTriggered.errcheck = self.check_status
            self.libtiepie.ScpSetMessageDataReady.restype = None
            self.libtiepie.ScpSetMessageDataReady.argtypes = [c_uint32, HWND, WPARAM, LPARAM]
            self.libtiepie.ScpSetMessageDataReady.errcheck = self.check_status
            self.libtiepie.ScpSetMessageDataOverflow.restype = None
            self.libtiepie.ScpSetMessageDataOverflow.argtypes = [c_uint32, HWND, WPARAM, LPARAM]
            self.libtiepie.ScpSetMessageDataOverflow.errcheck = self.check_status
            self.libtiepie.ScpSetMessageConnectionTestCompleted.restype = None
            self.libtiepie.ScpSetMessageConnectionTestCompleted.argtypes = [c_uint32, HWND, WPARAM, LPARAM]
            self.libtiepie.ScpSetMessageConnectionTestCompleted.errcheck = self.check_status
            self.libtiepie.ScpSetMessageTriggered.restype = None
            self.libtiepie.ScpSetMessageTriggered.argtypes = [c_uint32, HWND, WPARAM, LPARAM]
            self.libtiepie.ScpSetMessageTriggered.errcheck = self.check_status
        self.libtiepie.ScpStart.restype = c_uint8
        self.libtiepie.ScpStart.argtypes = [c_uint32]
        self.libtiepie.ScpStart.errcheck = self.check_status
        self.libtiepie.ScpStop.restype = c_uint8
        self.libtiepie.ScpStop.argtypes = [c_uint32]
        self.libtiepie.ScpStop.errcheck = self.check_status
        self.libtiepie.ScpForceTrigger.restype = c_uint8
        self.libtiepie.ScpForceTrigger.argtypes = [c_uint32]
        self.libtiepie.ScpForceTrigger.errcheck = self.check_status
        self.libtiepie.ScpGetMeasureModes.restype = c_uint32
        self.libtiepie.ScpGetMeasureModes.argtypes = [c_uint32]
        self.libtiepie.ScpGetMeasureModes.errcheck = self.check_status
        self.libtiepie.ScpGetMeasureMode.restype = c_uint32
        self.libtiepie.ScpGetMeasureMode.argtypes = [c_uint32]
        self.libtiepie.ScpGetMeasureMode.errcheck = self.check_status
        self.libtiepie.ScpSetMeasureMode.restype = c_uint32
        self.libtiepie.ScpSetMeasureMode.argtypes = [c_uint32, c_uint32]
        self.libtiepie.ScpSetMeasureMode.errcheck = self.check_status
        self.libtiepie.ScpIsRunning.restype = c_uint8
        self.libtiepie.ScpIsRunning.argtypes = [c_uint32]
        self.libtiepie.ScpIsRunning.errcheck = self.check_status
        self.libtiepie.ScpIsTriggered.restype = c_uint8
        self.libtiepie.ScpIsTriggered.argtypes = [c_uint32]
        self.libtiepie.ScpIsTriggered.errcheck = self.check_status
        self.libtiepie.ScpIsTimeOutTriggered.restype = c_uint8
        self.libtiepie.ScpIsTimeOutTriggered.argtypes = [c_uint32]
        self.libtiepie.ScpIsTimeOutTriggered.errcheck = self.check_status
        self.libtiepie.ScpIsForceTriggered.restype = c_uint8
        self.libtiepie.ScpIsForceTriggered.argtypes = [c_uint32]
        self.libtiepie.ScpIsForceTriggered.errcheck = self.check_status
        self.libtiepie.ScpIsDataReady.restype = c_uint8
        self.libtiepie.ScpIsDataReady.argtypes = [c_uint32]
        self.libtiepie.ScpIsDataReady.errcheck = self.check_status
        self.libtiepie.ScpIsDataOverflow.restype = c_uint8
        self.libtiepie.ScpIsDataOverflow.argtypes = [c_uint32]
        self.libtiepie.ScpIsDataOverflow.errcheck = self.check_status
        self.libtiepie.ScpGetAutoResolutionModes.restype = c_uint32
        self.libtiepie.ScpGetAutoResolutionModes.argtypes = [c_uint32]
        self.libtiepie.ScpGetAutoResolutionModes.errcheck = self.check_status
        self.libtiepie.ScpGetAutoResolutionMode.restype = c_uint32
        self.libtiepie.ScpGetAutoResolutionMode.argtypes = [c_uint32]
        self.libtiepie.ScpGetAutoResolutionMode.errcheck = self.check_status
        self.libtiepie.ScpSetAutoResolutionMode.restype = c_uint32
        self.libtiepie.ScpSetAutoResolutionMode.argtypes = [c_uint32, c_uint32]
        self.libtiepie.ScpSetAutoResolutionMode.errcheck = self.check_status
        self.libtiepie.ScpGetResolutions.restype = c_uint32
        self.libtiepie.ScpGetResolutions.argtypes = [c_uint32, c_void_p, c_uint32]
        self.libtiepie.ScpGetResolutions.errcheck = self.check_status
        self.libtiepie.ScpGetResolution.restype = c_uint8
        self.libtiepie.ScpGetResolution.argtypes = [c_uint32]
        self.libtiepie.ScpGetResolution.errcheck = self.check_status
        self.libtiepie.ScpSetResolution.restype = c_uint8
        self.libtiepie.ScpSetResolution.argtypes = [c_uint32, c_uint8]
        self.libtiepie.ScpSetResolution.errcheck = self.check_status
        self.libtiepie.ScpIsResolutionEnhanced.restype = c_uint8
        self.libtiepie.ScpIsResolutionEnhanced.argtypes = [c_uint32]
        self.libtiepie.ScpIsResolutionEnhanced.errcheck = self.check_status
        self.libtiepie.ScpIsResolutionEnhancedEx.restype = c_uint8
        self.libtiepie.ScpIsResolutionEnhancedEx.argtypes = [c_uint32, c_uint8]
        self.libtiepie.ScpIsResolutionEnhancedEx.errcheck = self.check_status
        self.libtiepie.ScpGetClockSources.restype = c_uint32
        self.libtiepie.ScpGetClockSources.argtypes = [c_uint32]
        self.libtiepie.ScpGetClockSources.errcheck = self.check_status
        self.libtiepie.ScpGetClockSource.restype = c_uint32
        self.libtiepie.ScpGetClockSource.argtypes = [c_uint32]
        self.libtiepie.ScpGetClockSource.errcheck = self.check_status
        self.libtiepie.ScpSetClockSource.restype = c_uint32
        self.libtiepie.ScpSetClockSource.argtypes = [c_uint32, c_uint32]
        self.libtiepie.ScpSetClockSource.errcheck = self.check_status
        self.libtiepie.ScpGetClockOutputs.restype = c_uint32
        self.libtiepie.ScpGetClockOutputs.argtypes = [c_uint32]
        self.libtiepie.ScpGetClockOutputs.errcheck = self.check_status
        self.libtiepie.ScpGetClockOutput.restype = c_uint32
        self.libtiepie.ScpGetClockOutput.argtypes = [c_uint32]
        self.libtiepie.ScpGetClockOutput.errcheck = self.check_status
        self.libtiepie.ScpSetClockOutput.restype = c_uint32
        self.libtiepie.ScpSetClockOutput.argtypes = [c_uint32, c_uint32]
        self.libtiepie.ScpSetClockOutput.errcheck = self.check_status
        self.libtiepie.ScpGetSampleFrequencyMax.restype = c_double
        self.libtiepie.ScpGetSampleFrequencyMax.argtypes = [c_uint32]
        self.libtiepie.ScpGetSampleFrequencyMax.errcheck = self.check_status
        self.libtiepie.ScpGetSampleFrequency.restype = c_double
        self.libtiepie.ScpGetSampleFrequency.argtypes = [c_uint32]
        self.libtiepie.ScpGetSampleFrequency.errcheck = self.check_status
        self.libtiepie.ScpSetSampleFrequency.restype = c_double
        self.libtiepie.ScpSetSampleFrequency.argtypes = [c_uint32, c_double]
        self.libtiepie.ScpSetSampleFrequency.errcheck = self.check_status
        self.libtiepie.ScpVerifySampleFrequency.restype = c_double
        self.libtiepie.ScpVerifySampleFrequency.argtypes = [c_uint32, c_double]
        self.libtiepie.ScpVerifySampleFrequency.errcheck = self.check_status
        self.libtiepie.ScpVerifySampleFrequencyEx.restype = c_double
        self.libtiepie.ScpVerifySampleFrequencyEx.argtypes = [c_uint32, c_double, c_uint32, c_uint8, c_void_p, c_uint16]
        self.libtiepie.ScpVerifySampleFrequencyEx.errcheck = self.check_status
        self.libtiepie.ScpVerifySampleFrequenciesEx.restype = None
        self.libtiepie.ScpVerifySampleFrequenciesEx.argtypes = [c_uint32, c_void_p, c_uint32, c_uint32, c_uint32,
                                                                c_uint8, c_void_p, c_uint16]
        self.libtiepie.ScpVerifySampleFrequenciesEx.errcheck = self.check_status
        self.libtiepie.ScpGetRecordLengthMax.restype = c_uint64
        self.libtiepie.ScpGetRecordLengthMax.argtypes = [c_uint32]
        self.libtiepie.ScpGetRecordLengthMax.errcheck = self.check_status
        self.libtiepie.ScpGetRecordLengthMaxEx.restype = c_uint64
        self.libtiepie.ScpGetRecordLengthMaxEx.argtypes = [c_uint32, c_uint32, c_uint8]
        self.libtiepie.ScpGetRecordLengthMaxEx.errcheck = self.check_status
        self.libtiepie.ScpGetRecordLength.restype = c_uint64
        self.libtiepie.ScpGetRecordLength.argtypes = [c_uint32]
        self.libtiepie.ScpGetRecordLength.errcheck = self.check_status
        self.libtiepie.ScpSetRecordLength.restype = c_uint64
        self.libtiepie.ScpSetRecordLength.argtypes = [c_uint32, c_uint64]
        self.libtiepie.ScpSetRecordLength.errcheck = self.check_status
        self.libtiepie.ScpVerifyRecordLength.restype = c_uint64
        self.libtiepie.ScpVerifyRecordLength.argtypes = [c_uint32, c_uint64]
        self.libtiepie.ScpVerifyRecordLength.errcheck = self.check_status
        self.libtiepie.ScpVerifyRecordLengthEx.restype = c_uint64
        self.libtiepie.ScpVerifyRecordLengthEx.argtypes = [c_uint32, c_uint64, c_uint32, c_uint8, c_void_p, c_uint16]
        self.libtiepie.ScpVerifyRecordLengthEx.errcheck = self.check_status
        self.libtiepie.ScpGetPreSampleRatio.restype = c_double
        self.libtiepie.ScpGetPreSampleRatio.argtypes = [c_uint32]
        self.libtiepie.ScpGetPreSampleRatio.errcheck = self.check_status
        self.libtiepie.ScpSetPreSampleRatio.restype = c_double
        self.libtiepie.ScpSetPreSampleRatio.argtypes = [c_uint32, c_double]
        self.libtiepie.ScpSetPreSampleRatio.errcheck = self.check_status
        self.libtiepie.ScpGetSegmentCountMax.restype = c_uint32
        self.libtiepie.ScpGetSegmentCountMax.argtypes = [c_uint32]
        self.libtiepie.ScpGetSegmentCountMax.errcheck = self.check_status
        self.libtiepie.ScpGetSegmentCountMaxEx.restype = c_uint32
        self.libtiepie.ScpGetSegmentCountMaxEx.argtypes = [c_uint32, c_uint32]
        self.libtiepie.ScpGetSegmentCountMaxEx.errcheck = self.check_status
        self.libtiepie.ScpGetSegmentCount.restype = c_uint32
        self.libtiepie.ScpGetSegmentCount.argtypes = [c_uint32]
        self.libtiepie.ScpGetSegmentCount.errcheck = self.check_status
        self.libtiepie.ScpSetSegmentCount.restype = c_uint32
        self.libtiepie.ScpSetSegmentCount.argtypes = [c_uint32, c_uint32]
        self.libtiepie.ScpSetSegmentCount.errcheck = self.check_status
        self.libtiepie.ScpVerifySegmentCount.restype = c_uint32
        self.libtiepie.ScpVerifySegmentCount.argtypes = [c_uint32, c_uint32]
        self.libtiepie.ScpVerifySegmentCount.errcheck = self.check_status
        self.libtiepie.ScpVerifySegmentCountEx2.restype = c_uint32
        self.libtiepie.ScpVerifySegmentCountEx2.argtypes = [c_uint32, c_uint32, c_uint32, c_uint64, c_void_p, c_uint16]
        self.libtiepie.ScpVerifySegmentCountEx2.errcheck = self.check_status
        self.libtiepie.ScpHasTrigger.restype = c_uint8
        self.libtiepie.ScpHasTrigger.argtypes = [c_uint32]
        self.libtiepie.ScpHasTrigger.errcheck = self.check_status
        self.libtiepie.ScpHasTriggerEx.restype = c_uint8
        self.libtiepie.ScpHasTriggerEx.argtypes = [c_uint32, c_uint32]
        self.libtiepie.ScpHasTriggerEx.errcheck = self.check_status
        self.libtiepie.ScpGetTriggerTimeOut.restype = c_double
        self.libtiepie.ScpGetTriggerTimeOut.argtypes = [c_uint32]
        self.libtiepie.ScpGetTriggerTimeOut.errcheck = self.check_status
        self.libtiepie.ScpSetTriggerTimeOut.restype = c_double
        self.libtiepie.ScpSetTriggerTimeOut.argtypes = [c_uint32, c_double]
        self.libtiepie.ScpSetTriggerTimeOut.errcheck = self.check_status
        self.libtiepie.ScpVerifyTriggerTimeOut.restype = c_double
        self.libtiepie.ScpVerifyTriggerTimeOut.argtypes = [c_uint32, c_double]
        self.libtiepie.ScpVerifyTriggerTimeOut.errcheck = self.check_status
        self.libtiepie.ScpVerifyTriggerTimeOutEx.restype = c_double
        self.libtiepie.ScpVerifyTriggerTimeOutEx.argtypes = [c_uint32, c_double, c_uint32, c_double]
        self.libtiepie.ScpVerifyTriggerTimeOutEx.errcheck = self.check_status
        self.libtiepie.ScpHasTriggerDelay.restype = c_uint8
        self.libtiepie.ScpHasTriggerDelay.argtypes = [c_uint32]
        self.libtiepie.ScpHasTriggerDelay.errcheck = self.check_status
        self.libtiepie.ScpHasTriggerDelayEx.restype = c_uint8
        self.libtiepie.ScpHasTriggerDelayEx.argtypes = [c_uint32, c_uint32]
        self.libtiepie.ScpHasTriggerDelayEx.errcheck = self.check_status
        self.libtiepie.ScpGetTriggerDelayMax.restype = c_double
        self.libtiepie.ScpGetTriggerDelayMax.argtypes = [c_uint32]
        self.libtiepie.ScpGetTriggerDelayMax.errcheck = self.check_status
        self.libtiepie.ScpGetTriggerDelayMaxEx.restype = c_double
        self.libtiepie.ScpGetTriggerDelayMaxEx.argtypes = [c_uint32, c_uint32, c_double]
        self.libtiepie.ScpGetTriggerDelayMaxEx.errcheck = self.check_status
        self.libtiepie.ScpGetTriggerDelay.restype = c_double
        self.libtiepie.ScpGetTriggerDelay.argtypes = [c_uint32]
        self.libtiepie.ScpGetTriggerDelay.errcheck = self.check_status
        self.libtiepie.ScpSetTriggerDelay.restype = c_double
        self.libtiepie.ScpSetTriggerDelay.argtypes = [c_uint32, c_double]
        self.libtiepie.ScpSetTriggerDelay.errcheck = self.check_status
        self.libtiepie.ScpVerifyTriggerDelay.restype = c_double
        self.libtiepie.ScpVerifyTriggerDelay.argtypes = [c_uint32, c_double]
        self.libtiepie.ScpVerifyTriggerDelay.errcheck = self.check_status
        self.libtiepie.ScpVerifyTriggerDelayEx.restype = c_double
        self.libtiepie.ScpVerifyTriggerDelayEx.argtypes = [c_uint32, c_double, c_uint32, c_double]
        self.libtiepie.ScpVerifyTriggerDelayEx.errcheck = self.check_status
        self.libtiepie.ScpHasTriggerHoldOff.restype = c_uint8
        self.libtiepie.ScpHasTriggerHoldOff.argtypes = [c_uint32]
        self.libtiepie.ScpHasTriggerHoldOff.errcheck = self.check_status
        self.libtiepie.ScpHasTriggerHoldOffEx.restype = c_uint8
        self.libtiepie.ScpHasTriggerHoldOffEx.argtypes = [c_uint32, c_uint32]
        self.libtiepie.ScpHasTriggerHoldOffEx.errcheck = self.check_status
        self.libtiepie.ScpGetTriggerHoldOffCountMax.restype = c_uint64
        self.libtiepie.ScpGetTriggerHoldOffCountMax.argtypes = [c_uint32]
        self.libtiepie.ScpGetTriggerHoldOffCountMax.errcheck = self.check_status
        self.libtiepie.ScpGetTriggerHoldOffCountMaxEx.restype = c_uint64
        self.libtiepie.ScpGetTriggerHoldOffCountMaxEx.argtypes = [c_uint32, c_uint32]
        self.libtiepie.ScpGetTriggerHoldOffCountMaxEx.errcheck = self.check_status
        self.libtiepie.ScpGetTriggerHoldOffCount.restype = c_uint64
        self.libtiepie.ScpGetTriggerHoldOffCount.argtypes = [c_uint32]
        self.libtiepie.ScpGetTriggerHoldOffCount.errcheck = self.check_status
        self.libtiepie.ScpSetTriggerHoldOffCount.restype = c_uint64
        self.libtiepie.ScpSetTriggerHoldOffCount.argtypes = [c_uint32, c_uint64]
        self.libtiepie.ScpSetTriggerHoldOffCount.errcheck = self.check_status
        self.libtiepie.ScpHasConnectionTest.restype = c_uint8
        self.libtiepie.ScpHasConnectionTest.argtypes = [c_uint32]
        self.libtiepie.ScpHasConnectionTest.errcheck = self.check_status
        self.libtiepie.ScpChHasConnectionTest.restype = c_uint8
        self.libtiepie.ScpChHasConnectionTest.argtypes = [c_uint32, c_uint16]
        self.libtiepie.ScpChHasConnectionTest.errcheck = self.check_status
        self.libtiepie.ScpStartConnectionTest.restype = c_uint8
        self.libtiepie.ScpStartConnectionTest.argtypes = [c_uint32]
        self.libtiepie.ScpStartConnectionTest.errcheck = self.check_status
        self.libtiepie.ScpStartConnectionTestEx.restype = c_uint8
        self.libtiepie.ScpStartConnectionTestEx.argtypes = [c_uint32, c_void_p, c_uint16]
        self.libtiepie.ScpStartConnectionTestEx.errcheck = self.check_status
        self.libtiepie.ScpIsConnectionTestCompleted.restype = c_uint8
        self.libtiepie.ScpIsConnectionTestCompleted.argtypes = [c_uint32]
        self.libtiepie.ScpIsConnectionTestCompleted.errcheck = self.check_status
        self.libtiepie.ScpGetConnectionTestData.restype = c_uint16
        self.libtiepie.ScpGetConnectionTestData.argtypes = [c_uint32, c_void_p, c_uint16]
        self.libtiepie.ScpGetConnectionTestData.errcheck = self.check_status
        self.libtiepie.GenGetConnectorType.restype = c_uint32
        self.libtiepie.GenGetConnectorType.argtypes = [c_uint32]
        self.libtiepie.GenGetConnectorType.errcheck = self.check_status
        self.libtiepie.GenIsDifferential.restype = c_uint8
        self.libtiepie.GenIsDifferential.argtypes = [c_uint32]
        self.libtiepie.GenIsDifferential.errcheck = self.check_status
        self.libtiepie.GenGetImpedance.restype = c_double
        self.libtiepie.GenGetImpedance.argtypes = [c_uint32]
        self.libtiepie.GenGetImpedance.errcheck = self.check_status
        self.libtiepie.GenGetResolution.restype = c_uint8
        self.libtiepie.GenGetResolution.argtypes = [c_uint32]
        self.libtiepie.GenGetResolution.errcheck = self.check_status
        self.libtiepie.GenGetOutputValueMin.restype = c_double
        self.libtiepie.GenGetOutputValueMin.argtypes = [c_uint32]
        self.libtiepie.GenGetOutputValueMin.errcheck = self.check_status
        self.libtiepie.GenGetOutputValueMax.restype = c_double
        self.libtiepie.GenGetOutputValueMax.argtypes = [c_uint32]
        self.libtiepie.GenGetOutputValueMax.errcheck = self.check_status
        self.libtiepie.GenGetOutputValueMinMax.restype = None
        self.libtiepie.GenGetOutputValueMinMax.argtypes = [c_uint32, c_void_p, c_void_p]
        self.libtiepie.GenGetOutputValueMinMax.errcheck = self.check_status
        self.libtiepie.GenIsControllable.restype = c_uint8
        self.libtiepie.GenIsControllable.argtypes = [c_uint32]
        self.libtiepie.GenIsControllable.errcheck = self.check_status
        self.libtiepie.GenGetStatus.restype = c_uint32
        self.libtiepie.GenGetStatus.argtypes = [c_uint32]
        self.libtiepie.GenGetStatus.errcheck = self.check_status
        self.libtiepie.GenGetOutputOn.restype = c_uint8
        self.libtiepie.GenGetOutputOn.argtypes = [c_uint32]
        self.libtiepie.GenGetOutputOn.errcheck = self.check_status
        self.libtiepie.GenSetOutputOn.restype = c_uint8
        self.libtiepie.GenSetOutputOn.argtypes = [c_uint32, c_uint8]
        self.libtiepie.GenSetOutputOn.errcheck = self.check_status
        self.libtiepie.GenGetOutputInvert.restype = c_uint8
        self.libtiepie.GenGetOutputInvert.argtypes = [c_uint32]
        self.libtiepie.GenGetOutputInvert.errcheck = self.check_status
        self.libtiepie.GenSetOutputInvert.restype = c_uint8
        self.libtiepie.GenSetOutputInvert.argtypes = [c_uint32, c_uint8]
        self.libtiepie.GenSetOutputInvert.errcheck = self.check_status
        self.libtiepie.GenStart.restype = c_uint8
        self.libtiepie.GenStart.argtypes = [c_uint32]
        self.libtiepie.GenStart.errcheck = self.check_status
        self.libtiepie.GenStop.restype = c_uint8
        self.libtiepie.GenStop.argtypes = [c_uint32]
        self.libtiepie.GenStop.errcheck = self.check_status
        self.libtiepie.GenGetSignalTypes.restype = c_uint32
        self.libtiepie.GenGetSignalTypes.argtypes = [c_uint32]
        self.libtiepie.GenGetSignalTypes.errcheck = self.check_status
        self.libtiepie.GenGetSignalType.restype = c_uint32
        self.libtiepie.GenGetSignalType.argtypes = [c_uint32]
        self.libtiepie.GenGetSignalType.errcheck = self.check_status
        self.libtiepie.GenSetSignalType.restype = c_uint32
        self.libtiepie.GenSetSignalType.argtypes = [c_uint32, c_uint32]
        self.libtiepie.GenSetSignalType.errcheck = self.check_status
        self.libtiepie.GenGetAmplitudeMin.restype = c_double
        self.libtiepie.GenGetAmplitudeMin.argtypes = [c_uint32]
        self.libtiepie.GenGetAmplitudeMin.errcheck = self.check_status
        self.libtiepie.GenGetAmplitudeMax.restype = c_double
        self.libtiepie.GenGetAmplitudeMax.argtypes = [c_uint32]
        self.libtiepie.GenGetAmplitudeMax.errcheck = self.check_status
        self.libtiepie.GenGetAmplitudeMinMaxEx.restype = None
        self.libtiepie.GenGetAmplitudeMinMaxEx.argtypes = [c_uint32, c_uint32, c_void_p, c_void_p]
        self.libtiepie.GenGetAmplitudeMinMaxEx.errcheck = self.check_status
        self.libtiepie.GenGetAmplitude.restype = c_double
        self.libtiepie.GenGetAmplitude.argtypes = [c_uint32]
        self.libtiepie.GenGetAmplitude.errcheck = self.check_status
        self.libtiepie.GenSetAmplitude.restype = c_double
        self.libtiepie.GenSetAmplitude.argtypes = [c_uint32, c_double]
        self.libtiepie.GenSetAmplitude.errcheck = self.check_status
        self.libtiepie.GenVerifyAmplitude.restype = c_double
        self.libtiepie.GenVerifyAmplitude.argtypes = [c_uint32, c_double]
        self.libtiepie.GenVerifyAmplitude.errcheck = self.check_status
        self.libtiepie.GenVerifyAmplitudeEx.restype = c_double
        self.libtiepie.GenVerifyAmplitudeEx.argtypes = [c_uint32, c_double, c_uint32, c_uint32, c_double]
        self.libtiepie.GenVerifyAmplitudeEx.errcheck = self.check_status
        self.libtiepie.GenGetAmplitudeRanges.restype = c_uint32
        self.libtiepie.GenGetAmplitudeRanges.argtypes = [c_uint32, c_void_p, c_uint32]
        self.libtiepie.GenGetAmplitudeRanges.errcheck = self.check_status
        self.libtiepie.GenGetAmplitudeRange.restype = c_double
        self.libtiepie.GenGetAmplitudeRange.argtypes = [c_uint32]
        self.libtiepie.GenGetAmplitudeRange.errcheck = self.check_status
        self.libtiepie.GenSetAmplitudeRange.restype = c_double
        self.libtiepie.GenSetAmplitudeRange.argtypes = [c_uint32, c_double]
        self.libtiepie.GenSetAmplitudeRange.errcheck = self.check_status
        self.libtiepie.GenGetAmplitudeAutoRanging.restype = c_uint8
        self.libtiepie.GenGetAmplitudeAutoRanging.argtypes = [c_uint32]
        self.libtiepie.GenGetAmplitudeAutoRanging.errcheck = self.check_status
        self.libtiepie.GenSetAmplitudeAutoRanging.restype = c_uint8
        self.libtiepie.GenSetAmplitudeAutoRanging.argtypes = [c_uint32, c_uint8]
        self.libtiepie.GenSetAmplitudeAutoRanging.errcheck = self.check_status
        self.libtiepie.GenGetOffsetMin.restype = c_double
        self.libtiepie.GenGetOffsetMin.argtypes = [c_uint32]
        self.libtiepie.GenGetOffsetMin.errcheck = self.check_status
        self.libtiepie.GenGetOffsetMax.restype = c_double
        self.libtiepie.GenGetOffsetMax.argtypes = [c_uint32]
        self.libtiepie.GenGetOffsetMax.errcheck = self.check_status
        self.libtiepie.GenGetOffsetMinMaxEx.restype = None
        self.libtiepie.GenGetOffsetMinMaxEx.argtypes = [c_uint32, c_uint32, c_void_p, c_void_p]
        self.libtiepie.GenGetOffsetMinMaxEx.errcheck = self.check_status
        self.libtiepie.GenGetOffset.restype = c_double
        self.libtiepie.GenGetOffset.argtypes = [c_uint32]
        self.libtiepie.GenGetOffset.errcheck = self.check_status
        self.libtiepie.GenSetOffset.restype = c_double
        self.libtiepie.GenSetOffset.argtypes = [c_uint32, c_double]
        self.libtiepie.GenSetOffset.errcheck = self.check_status
        self.libtiepie.GenVerifyOffset.restype = c_double
        self.libtiepie.GenVerifyOffset.argtypes = [c_uint32, c_double]
        self.libtiepie.GenVerifyOffset.errcheck = self.check_status
        self.libtiepie.GenVerifyOffsetEx.restype = c_double
        self.libtiepie.GenVerifyOffsetEx.argtypes = [c_uint32, c_double, c_uint32, c_double]
        self.libtiepie.GenVerifyOffsetEx.errcheck = self.check_status
        self.libtiepie.GenGetFrequencyModes.restype = c_uint32
        self.libtiepie.GenGetFrequencyModes.argtypes = [c_uint32]
        self.libtiepie.GenGetFrequencyModes.errcheck = self.check_status
        self.libtiepie.GenGetFrequencyModesEx.restype = c_uint32
        self.libtiepie.GenGetFrequencyModesEx.argtypes = [c_uint32, c_uint32]
        self.libtiepie.GenGetFrequencyModesEx.errcheck = self.check_status
        self.libtiepie.GenGetFrequencyMode.restype = c_uint32
        self.libtiepie.GenGetFrequencyMode.argtypes = [c_uint32]
        self.libtiepie.GenGetFrequencyMode.errcheck = self.check_status
        self.libtiepie.GenSetFrequencyMode.restype = c_uint32
        self.libtiepie.GenSetFrequencyMode.argtypes = [c_uint32, c_uint32]
        self.libtiepie.GenSetFrequencyMode.errcheck = self.check_status
        self.libtiepie.GenGetFrequencyMin.restype = c_double
        self.libtiepie.GenGetFrequencyMin.argtypes = [c_uint32]
        self.libtiepie.GenGetFrequencyMin.errcheck = self.check_status
        self.libtiepie.GenGetFrequencyMax.restype = c_double
        self.libtiepie.GenGetFrequencyMax.argtypes = [c_uint32]
        self.libtiepie.GenGetFrequencyMax.errcheck = self.check_status
        self.libtiepie.GenGetFrequencyMinMax.restype = None
        self.libtiepie.GenGetFrequencyMinMax.argtypes = [c_uint32, c_uint32, c_void_p, c_void_p]
        self.libtiepie.GenGetFrequencyMinMax.errcheck = self.check_status
        self.libtiepie.GenGetFrequencyMinMaxEx.restype = None
        self.libtiepie.GenGetFrequencyMinMaxEx.argtypes = [c_uint32, c_uint32, c_uint32, c_void_p, c_void_p]
        self.libtiepie.GenGetFrequencyMinMaxEx.errcheck = self.check_status
        self.libtiepie.GenGetFrequency.restype = c_double
        self.libtiepie.GenGetFrequency.argtypes = [c_uint32]
        self.libtiepie.GenGetFrequency.errcheck = self.check_status
        self.libtiepie.GenSetFrequency.restype = c_double
        self.libtiepie.GenSetFrequency.argtypes = [c_uint32, c_double]
        self.libtiepie.GenSetFrequency.errcheck = self.check_status
        self.libtiepie.GenVerifyFrequency.restype = c_double
        self.libtiepie.GenVerifyFrequency.argtypes = [c_uint32, c_double]
        self.libtiepie.GenVerifyFrequency.errcheck = self.check_status
        self.libtiepie.GenVerifyFrequencyEx2.restype = c_double
        self.libtiepie.GenVerifyFrequencyEx2.argtypes = [c_uint32, c_double, c_uint32, c_uint32, c_uint64, c_double]
        self.libtiepie.GenVerifyFrequencyEx2.errcheck = self.check_status
        self.libtiepie.GenGetPhaseMin.restype = c_double
        self.libtiepie.GenGetPhaseMin.argtypes = [c_uint32]
        self.libtiepie.GenGetPhaseMin.errcheck = self.check_status
        self.libtiepie.GenGetPhaseMax.restype = c_double
        self.libtiepie.GenGetPhaseMax.argtypes = [c_uint32]
        self.libtiepie.GenGetPhaseMax.errcheck = self.check_status
        self.libtiepie.GenGetPhaseMinMaxEx.restype = None
        self.libtiepie.GenGetPhaseMinMaxEx.argtypes = [c_uint32, c_uint32, c_void_p, c_void_p]
        self.libtiepie.GenGetPhaseMinMaxEx.errcheck = self.check_status
        self.libtiepie.GenGetPhase.restype = c_double
        self.libtiepie.GenGetPhase.argtypes = [c_uint32]
        self.libtiepie.GenGetPhase.errcheck = self.check_status
        self.libtiepie.GenSetPhase.restype = c_double
        self.libtiepie.GenSetPhase.argtypes = [c_uint32, c_double]
        self.libtiepie.GenSetPhase.errcheck = self.check_status
        self.libtiepie.GenVerifyPhase.restype = c_double
        self.libtiepie.GenVerifyPhase.argtypes = [c_uint32, c_double]
        self.libtiepie.GenVerifyPhase.errcheck = self.check_status
        self.libtiepie.GenVerifyPhaseEx.restype = c_double
        self.libtiepie.GenVerifyPhaseEx.argtypes = [c_uint32, c_double, c_uint32]
        self.libtiepie.GenVerifyPhaseEx.errcheck = self.check_status
        self.libtiepie.GenGetSymmetryMin.restype = c_double
        self.libtiepie.GenGetSymmetryMin.argtypes = [c_uint32]
        self.libtiepie.GenGetSymmetryMin.errcheck = self.check_status
        self.libtiepie.GenGetSymmetryMax.restype = c_double
        self.libtiepie.GenGetSymmetryMax.argtypes = [c_uint32]
        self.libtiepie.GenGetSymmetryMax.errcheck = self.check_status
        self.libtiepie.GenGetSymmetryMinMaxEx.restype = None
        self.libtiepie.GenGetSymmetryMinMaxEx.argtypes = [c_uint32, c_uint32, c_void_p, c_void_p]
        self.libtiepie.GenGetSymmetryMinMaxEx.errcheck = self.check_status
        self.libtiepie.GenGetSymmetry.restype = c_double
        self.libtiepie.GenGetSymmetry.argtypes = [c_uint32]
        self.libtiepie.GenGetSymmetry.errcheck = self.check_status
        self.libtiepie.GenSetSymmetry.restype = c_double
        self.libtiepie.GenSetSymmetry.argtypes = [c_uint32, c_double]
        self.libtiepie.GenSetSymmetry.errcheck = self.check_status
        self.libtiepie.GenVerifySymmetry.restype = c_double
        self.libtiepie.GenVerifySymmetry.argtypes = [c_uint32, c_double]
        self.libtiepie.GenVerifySymmetry.errcheck = self.check_status
        self.libtiepie.GenVerifySymmetryEx.restype = c_double
        self.libtiepie.GenVerifySymmetryEx.argtypes = [c_uint32, c_double, c_uint32]
        self.libtiepie.GenVerifySymmetryEx.errcheck = self.check_status
        self.libtiepie.GenGetWidthMin.restype = c_double
        self.libtiepie.GenGetWidthMin.argtypes = [c_uint32]
        self.libtiepie.GenGetWidthMin.errcheck = self.check_status
        self.libtiepie.GenGetWidthMax.restype = c_double
        self.libtiepie.GenGetWidthMax.argtypes = [c_uint32]
        self.libtiepie.GenGetWidthMax.errcheck = self.check_status
        self.libtiepie.GenGetWidthMinMaxEx.restype = None
        self.libtiepie.GenGetWidthMinMaxEx.argtypes = [c_uint32, c_uint32, c_double, c_void_p, c_void_p]
        self.libtiepie.GenGetWidthMinMaxEx.errcheck = self.check_status
        self.libtiepie.GenGetWidth.restype = c_double
        self.libtiepie.GenGetWidth.argtypes = [c_uint32]
        self.libtiepie.GenGetWidth.errcheck = self.check_status
        self.libtiepie.GenSetWidth.restype = c_double
        self.libtiepie.GenSetWidth.argtypes = [c_uint32, c_double]
        self.libtiepie.GenSetWidth.errcheck = self.check_status
        self.libtiepie.GenVerifyWidth.restype = c_double
        self.libtiepie.GenVerifyWidth.argtypes = [c_uint32, c_double]
        self.libtiepie.GenVerifyWidth.errcheck = self.check_status
        self.libtiepie.GenVerifyWidthEx.restype = c_double
        self.libtiepie.GenVerifyWidthEx.argtypes = [c_uint32, c_double, c_uint32, c_double]
        self.libtiepie.GenVerifyWidthEx.errcheck = self.check_status
        self.libtiepie.GenGetDataLengthMin.restype = c_uint64
        self.libtiepie.GenGetDataLengthMin.argtypes = [c_uint32]
        self.libtiepie.GenGetDataLengthMin.errcheck = self.check_status
        self.libtiepie.GenGetDataLengthMax.restype = c_uint64
        self.libtiepie.GenGetDataLengthMax.argtypes = [c_uint32]
        self.libtiepie.GenGetDataLengthMax.errcheck = self.check_status
        self.libtiepie.GenGetDataLengthMinMaxEx.restype = None
        self.libtiepie.GenGetDataLengthMinMaxEx.argtypes = [c_uint32, c_uint32, c_void_p, c_void_p]
        self.libtiepie.GenGetDataLengthMinMaxEx.errcheck = self.check_status
        self.libtiepie.GenGetDataLength.restype = c_uint64
        self.libtiepie.GenGetDataLength.argtypes = [c_uint32]
        self.libtiepie.GenGetDataLength.errcheck = self.check_status
        self.libtiepie.GenVerifyDataLength.restype = c_uint64
        self.libtiepie.GenVerifyDataLength.argtypes = [c_uint32, c_uint64]
        self.libtiepie.GenVerifyDataLength.errcheck = self.check_status
        self.libtiepie.GenVerifyDataLengthEx.restype = c_uint64
        self.libtiepie.GenVerifyDataLengthEx.argtypes = [c_uint32, c_uint64, c_uint32]
        self.libtiepie.GenVerifyDataLengthEx.errcheck = self.check_status
        self.libtiepie.GenSetData.restype = None
        self.libtiepie.GenSetData.argtypes = [c_uint32, c_void_p, c_uint64]
        self.libtiepie.GenSetData.errcheck = self.check_status
        self.libtiepie.GenSetDataEx.restype = None
        self.libtiepie.GenSetDataEx.argtypes = [c_uint32, c_void_p, c_uint64, c_uint32, c_uint32]
        self.libtiepie.GenSetDataEx.errcheck = self.check_status
        self.libtiepie.GenGetDataRawType.restype = c_uint32
        self.libtiepie.GenGetDataRawType.argtypes = [c_uint32]
        self.libtiepie.GenGetDataRawType.errcheck = self.check_status
        self.libtiepie.GenGetDataRawValueRange.restype = None
        self.libtiepie.GenGetDataRawValueRange.argtypes = [c_uint32, c_void_p, c_void_p, c_void_p]
        self.libtiepie.GenGetDataRawValueRange.errcheck = self.check_status
        self.libtiepie.GenGetDataRawValueMin.restype = c_int64
        self.libtiepie.GenGetDataRawValueMin.argtypes = [c_uint32]
        self.libtiepie.GenGetDataRawValueMin.errcheck = self.check_status
        self.libtiepie.GenGetDataRawValueZero.restype = c_int64
        self.libtiepie.GenGetDataRawValueZero.argtypes = [c_uint32]
        self.libtiepie.GenGetDataRawValueZero.errcheck = self.check_status
        self.libtiepie.GenGetDataRawValueMax.restype = c_int64
        self.libtiepie.GenGetDataRawValueMax.argtypes = [c_uint32]
        self.libtiepie.GenGetDataRawValueMax.errcheck = self.check_status
        self.libtiepie.GenSetDataRaw.restype = None
        self.libtiepie.GenSetDataRaw.argtypes = [c_uint32, c_void_p, c_uint64]
        self.libtiepie.GenSetDataRaw.errcheck = self.check_status
        self.libtiepie.GenSetDataRawEx.restype = None
        self.libtiepie.GenSetDataRawEx.argtypes = [c_uint32, c_void_p, c_uint64, c_uint32, c_uint32]
        self.libtiepie.GenSetDataRawEx.errcheck = self.check_status
        self.libtiepie.GenGetModes.restype = c_uint64
        self.libtiepie.GenGetModes.argtypes = [c_uint32]
        self.libtiepie.GenGetModes.errcheck = self.check_status
        self.libtiepie.GenGetModesEx.restype = c_uint64
        self.libtiepie.GenGetModesEx.argtypes = [c_uint32, c_uint32, c_uint32]
        self.libtiepie.GenGetModesEx.errcheck = self.check_status
        self.libtiepie.GenGetModesNative.restype = c_uint64
        self.libtiepie.GenGetModesNative.argtypes = [c_uint32]
        self.libtiepie.GenGetModesNative.errcheck = self.check_status
        self.libtiepie.GenGetMode.restype = c_uint64
        self.libtiepie.GenGetMode.argtypes = [c_uint32]
        self.libtiepie.GenGetMode.errcheck = self.check_status
        self.libtiepie.GenSetMode.restype = c_uint64
        self.libtiepie.GenSetMode.argtypes = [c_uint32, c_uint64]
        self.libtiepie.GenSetMode.errcheck = self.check_status
        self.libtiepie.GenIsBurstActive.restype = c_uint8
        self.libtiepie.GenIsBurstActive.argtypes = [c_uint32]
        self.libtiepie.GenIsBurstActive.errcheck = self.check_status
        self.libtiepie.GenGetBurstCountMin.restype = c_uint64
        self.libtiepie.GenGetBurstCountMin.argtypes = [c_uint32]
        self.libtiepie.GenGetBurstCountMin.errcheck = self.check_status
        self.libtiepie.GenGetBurstCountMax.restype = c_uint64
        self.libtiepie.GenGetBurstCountMax.argtypes = [c_uint32]
        self.libtiepie.GenGetBurstCountMax.errcheck = self.check_status
        self.libtiepie.GenGetBurstCountMinMaxEx.restype = None
        self.libtiepie.GenGetBurstCountMinMaxEx.argtypes = [c_uint32, c_uint64, c_void_p, c_void_p]
        self.libtiepie.GenGetBurstCountMinMaxEx.errcheck = self.check_status
        self.libtiepie.GenGetBurstCount.restype = c_uint64
        self.libtiepie.GenGetBurstCount.argtypes = [c_uint32]
        self.libtiepie.GenGetBurstCount.errcheck = self.check_status
        self.libtiepie.GenSetBurstCount.restype = c_uint64
        self.libtiepie.GenSetBurstCount.argtypes = [c_uint32, c_uint64]
        self.libtiepie.GenSetBurstCount.errcheck = self.check_status
        self.libtiepie.GenGetBurstSampleCountMin.restype = c_uint64
        self.libtiepie.GenGetBurstSampleCountMin.argtypes = [c_uint32]
        self.libtiepie.GenGetBurstSampleCountMin.errcheck = self.check_status
        self.libtiepie.GenGetBurstSampleCountMax.restype = c_uint64
        self.libtiepie.GenGetBurstSampleCountMax.argtypes = [c_uint32]
        self.libtiepie.GenGetBurstSampleCountMax.errcheck = self.check_status
        self.libtiepie.GenGetBurstSampleCountMinMaxEx.restype = None
        self.libtiepie.GenGetBurstSampleCountMinMaxEx.argtypes = [c_uint32, c_uint64, c_void_p, c_void_p]
        self.libtiepie.GenGetBurstSampleCountMinMaxEx.errcheck = self.check_status
        self.libtiepie.GenGetBurstSampleCount.restype = c_uint64
        self.libtiepie.GenGetBurstSampleCount.argtypes = [c_uint32]
        self.libtiepie.GenGetBurstSampleCount.errcheck = self.check_status
        self.libtiepie.GenSetBurstSampleCount.restype = c_uint64
        self.libtiepie.GenSetBurstSampleCount.argtypes = [c_uint32, c_uint64]
        self.libtiepie.GenSetBurstSampleCount.errcheck = self.check_status
        self.libtiepie.GenGetBurstSegmentCountMin.restype = c_uint64
        self.libtiepie.GenGetBurstSegmentCountMin.argtypes = [c_uint32]
        self.libtiepie.GenGetBurstSegmentCountMin.errcheck = self.check_status
        self.libtiepie.GenGetBurstSegmentCountMax.restype = c_uint64
        self.libtiepie.GenGetBurstSegmentCountMax.argtypes = [c_uint32]
        self.libtiepie.GenGetBurstSegmentCountMax.errcheck = self.check_status
        self.libtiepie.GenGetBurstSegmentCountMinMaxEx.restype = None
        self.libtiepie.GenGetBurstSegmentCountMinMaxEx.argtypes = [c_uint32, c_uint64, c_uint32, c_uint32, c_double,
                                                                   c_uint64, c_void_p, c_void_p]
        self.libtiepie.GenGetBurstSegmentCountMinMaxEx.errcheck = self.check_status
        self.libtiepie.GenGetBurstSegmentCount.restype = c_uint64
        self.libtiepie.GenGetBurstSegmentCount.argtypes = [c_uint32]
        self.libtiepie.GenGetBurstSegmentCount.errcheck = self.check_status
        self.libtiepie.GenSetBurstSegmentCount.restype = c_uint64
        self.libtiepie.GenSetBurstSegmentCount.argtypes = [c_uint32, c_uint64]
        self.libtiepie.GenSetBurstSegmentCount.errcheck = self.check_status
        self.libtiepie.GenVerifyBurstSegmentCount.restype = c_uint64
        self.libtiepie.GenVerifyBurstSegmentCount.argtypes = [c_uint32, c_uint64]
        self.libtiepie.GenVerifyBurstSegmentCount.errcheck = self.check_status
        self.libtiepie.GenVerifyBurstSegmentCountEx.restype = c_uint64
        self.libtiepie.GenVerifyBurstSegmentCountEx.argtypes = [c_uint32, c_uint64, c_uint64, c_uint32, c_uint32,
                                                                c_double, c_uint64]
        self.libtiepie.GenVerifyBurstSegmentCountEx.errcheck = self.check_status
        self.libtiepie.GenSetCallbackBurstCompleted.restype = None
        self.libtiepie.GenSetCallbackBurstCompleted.argtypes = [c_uint32, Callback, c_void_p]
        self.libtiepie.GenSetCallbackBurstCompleted.errcheck = self.check_status
        if platform.system() == 'Linux':
            self.libtiepie.GenSetEventBurstCompleted.restype = None
            self.libtiepie.GenSetEventBurstCompleted.argtypes = [c_uint32, c_int]
            self.libtiepie.GenSetEventBurstCompleted.errcheck = self.check_status
        if platform.system() == 'Windows':
            self.libtiepie.GenSetEventBurstCompleted.restype = None
            self.libtiepie.GenSetEventBurstCompleted.argtypes = [c_uint32, HANDLE]
            self.libtiepie.GenSetEventBurstCompleted.errcheck = self.check_status
            self.libtiepie.GenSetMessageBurstCompleted.restype = None
            self.libtiepie.GenSetMessageBurstCompleted.argtypes = [c_uint32, HWND, WPARAM, LPARAM]
            self.libtiepie.GenSetMessageBurstCompleted.errcheck = self.check_status
        self.libtiepie.GenSetCallbackControllableChanged.restype = None
        self.libtiepie.GenSetCallbackControllableChanged.argtypes = [c_uint32, Callback, c_void_p]
        self.libtiepie.GenSetCallbackControllableChanged.errcheck = self.check_status
        if platform.system() == 'Linux':
            self.libtiepie.GenSetEventControllableChanged.restype = None
            self.libtiepie.GenSetEventControllableChanged.argtypes = [c_uint32, c_int]
            self.libtiepie.GenSetEventControllableChanged.errcheck = self.check_status
        if platform.system() == 'Windows':
            self.libtiepie.GenSetEventControllableChanged.restype = None
            self.libtiepie.GenSetEventControllableChanged.argtypes = [c_uint32, HANDLE]
            self.libtiepie.GenSetEventControllableChanged.errcheck = self.check_status
            self.libtiepie.GenSetMessageControllableChanged.restype = None
            self.libtiepie.GenSetMessageControllableChanged.argtypes = [c_uint32, HWND, WPARAM, LPARAM]
            self.libtiepie.GenSetMessageControllableChanged.errcheck = self.check_status
        self.libtiepie.I2CIsInternalAddress.restype = c_uint8
        self.libtiepie.I2CIsInternalAddress.argtypes = [c_uint32, c_uint16]
        self.libtiepie.I2CIsInternalAddress.errcheck = self.check_status
        self.libtiepie.I2CRead.restype = c_uint8
        self.libtiepie.I2CRead.argtypes = [c_uint32, c_uint16, c_void_p, c_uint32, c_uint8]
        self.libtiepie.I2CRead.errcheck = self.check_status
        self.libtiepie.I2CReadByte.restype = c_uint8
        self.libtiepie.I2CReadByte.argtypes = [c_uint32, c_uint16, c_void_p]
        self.libtiepie.I2CReadByte.errcheck = self.check_status
        self.libtiepie.I2CReadWord.restype = c_uint8
        self.libtiepie.I2CReadWord.argtypes = [c_uint32, c_uint16, c_void_p]
        self.libtiepie.I2CReadWord.errcheck = self.check_status
        self.libtiepie.I2CWrite.restype = c_uint8
        self.libtiepie.I2CWrite.argtypes = [c_uint32, c_uint16, c_void_p, c_uint32, c_uint8]
        self.libtiepie.I2CWrite.errcheck = self.check_status
        self.libtiepie.I2CWriteByte.restype = c_uint8
        self.libtiepie.I2CWriteByte.argtypes = [c_uint32, c_uint16, c_uint8]
        self.libtiepie.I2CWriteByte.errcheck = self.check_status
        self.libtiepie.I2CWriteByteByte.restype = c_uint8
        self.libtiepie.I2CWriteByteByte.argtypes = [c_uint32, c_uint16, c_uint8, c_uint8]
        self.libtiepie.I2CWriteByteByte.errcheck = self.check_status
        self.libtiepie.I2CWriteByteWord.restype = c_uint8
        self.libtiepie.I2CWriteByteWord.argtypes = [c_uint32, c_uint16, c_uint8, c_uint16]
        self.libtiepie.I2CWriteByteWord.errcheck = self.check_status
        self.libtiepie.I2CWriteWord.restype = c_uint8
        self.libtiepie.I2CWriteWord.argtypes = [c_uint32, c_uint16, c_uint16]
        self.libtiepie.I2CWriteWord.errcheck = self.check_status
        self.libtiepie.I2CGetSpeedMax.restype = c_double
        self.libtiepie.I2CGetSpeedMax.argtypes = [c_uint32]
        self.libtiepie.I2CGetSpeedMax.errcheck = self.check_status
        self.libtiepie.I2CGetSpeed.restype = c_double
        self.libtiepie.I2CGetSpeed.argtypes = [c_uint32]
        self.libtiepie.I2CGetSpeed.errcheck = self.check_status
        self.libtiepie.I2CSetSpeed.restype = c_double
        self.libtiepie.I2CSetSpeed.argtypes = [c_uint32, c_double]
        self.libtiepie.I2CSetSpeed.errcheck = self.check_status
        self.libtiepie.I2CVerifySpeed.restype = c_double
        self.libtiepie.I2CVerifySpeed.argtypes = [c_uint32, c_double]
        self.libtiepie.I2CVerifySpeed.errcheck = self.check_status
        self.libtiepie.HlpPointerArrayNew.restype = c_void_p
        self.libtiepie.HlpPointerArrayNew.argtypes = [c_uint32]
        self.libtiepie.HlpPointerArrayNew.errcheck = self.check_status
        self.libtiepie.HlpPointerArraySet.restype = None
        self.libtiepie.HlpPointerArraySet.argtypes = [c_void_p, c_uint32, c_void_p]
        self.libtiepie.HlpPointerArraySet.errcheck = self.check_status
        self.libtiepie.HlpPointerArrayDelete.restype = None
        self.libtiepie.HlpPointerArrayDelete.argtypes = [c_void_p]
        self.libtiepie.HlpPointerArrayDelete.errcheck = self.check_status

        # Init the library
        self.libtiepie.LibInit()

    def check_status(self, result, func, args):
        """Checks the status after calling a library function.

        This function is not intended as standalone function. It is
        a callable to be assigned to the :py:attr:`ctypes._FuncPtr.errcheck` attribute of the foreign function
        definitions.

        Args:
            result: what the foreign function returns, as specified by the restype attribute
            func: the foreign function object itself
            args:  tuple containing the parameters originally passed to the function call

        Returns:
            The unaltered result returned by the foreign function.
        """

        status_code = self.libtiepie.LibGetLastStatus()

        # From API documentation:
        # 0 means ok
        # <0 means error
        # >0 means ok, but with a side effect
        if status_code != 0:
            status_str = '[' + str(status_code) + ']: ' + str(self.libtiepie.LibGetLastStatusStr())
            if status_code > 0:
                warnings.warn(status_str)
            else:
                raise IOError(status_str)

        return result
